title: "Jinal Desai"
author: "Jinal Desai"
description: "This is my technical blog portraying some summary from the original blog jinaldesai.com. I'll cover articles on topics like Google Cloud Platform, DevOps, etc." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "contact@jinaldesai.com"
twitter_username: "jinaldesailive"
github_username: "jinaldesailive"
linkedin_username: "jinaldesailive"
facebook_username: jinaldesailive
#flickr_username: username
#instagram_username: jinaldesailive
website: jinaldesai.com
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
